export default [
    'strata│strata│strata│perception',
    '////altération\\\\\\\\construction////',
    '≡≡≡≡superposition≡≡≡≡enchevêtrement',
    'flux━━━contrainte━━━divergence',
    '▓▒░ opacity of representation ░▒▓',
    '┼┼┼ interdependence ┼┼┼ relation',
    'real ‖ screen ‖ window ‖ écran',
    '⊞⊟⊠⊡ geometric primitives',
    '∿∿∿ chaotic trajectories ∿∿∿',
    'perspectivesXperspectivesXperspectives',
    '|||brouhaha|||cacophonie|||flux|||',
    '▪▫▪ modular deconstruction ▫▪▫',
    '═══╬═══ threshold ═══╬═══',
    'Perlin>>>>noise>>>>flow>>>>field',
    '⟨⟨⟨ accumulation ⟩⟩⟩ stratification',
    '↯ collision of logics ↯',
    '∆∇ depth on plane ∇∆',
    'iteration[[[[[[[protocol]]]]]]]',
    '⋮⋮⋮ multiplicité du réel ⋮⋮⋮',
    '≋≋≋ instability ≋≋≋ ambiguity',
    '⊕⊖⊗ ontological pluralism',

    '↻ protocol ↻ mutation ↻ system',
    '≡≡≡≡superposition≡≡≡≡entanglement',
    'flux━━━constraint━━━divergence',
    '▓▒░ opacity of representation ░▒▓',
    '┼┼┼ interdependence ┼┼┼ relation',
    'real ‖ screen ‖ window ‖ layer',
    '⊞⊟⊠⊡ geometric primitives',
    '∿∿∿ chaotic trajectories ∿∿∿',
    'perspectivesXperspectivesXperspectives',
    '|||cacophony|||flow|||noise|||',
    '▪▫▪ modular deconstruction ▫▪▫',
    '═══╬═══ threshold ═══╬═══',
    'Perlin>>>>noise>>>>flow>>>>field',
    '⟨⟨⟨ accumulation ⟩⟩⟩ stratification',
    '↯ collision of logics ↯',
    '∆∇ depth on plane ∇∆',
    'iteration[[[[[[[protocol]]]]]]]',
    '⋮⋮⋮ multiplicity of reality ⋮⋮⋮',
    '≋≋≋ instability ≋≋≋ ambiguity',
    '⊕⊖⊗ ontological pluralism'
]
