export default [
 
 ["Honolulu", false, -10, "US"],
  ["Anchorage", false, -9, "US"],   
  ["Tijuana", false, -8, "MX"],
  ["Los Angeles", false, -8, "US"], 
  ["Vancouver", false, -7, "CA"], 
  ["Edmonton", false, -7, "CA"],
  ["Mazatlán", false, -7, "MX"],
  ["Phoenix", false, -7, "US"], 
  ["Ciudad de México", false, -6, "MX"],
  ["Chicago", false, -6, "US"],
  ["New York", false, -5, "US"],
  ["Detroit", false, -5, "US"],
  ["Guayaquil", false, -5, "EC"],
  ["Shangai", "上海", 8, "CN"],
  [
    "Euronext", 
    'Amsterdam<br>Brussels<br>Dublin<br>Lisbon<br>Milan<br>Oslo<br>Paris', 1, "EU"],
  ["Tokyo", "東京都", 9, "JP"],
  ["Shenzhen", "深圳市", 8, "CN"],
  ["Mumbai", false, 5.30, "IN"],
  //["Scoresby", false, -1, "GL"],
  //["Praia", false, -1, "CV"],
  //["São Miguel", false, -2, "PT"],
  //["Nuuk", false, -2, "GL"],
  ["Buenos Aires", false, -3, "AR"],
  ["Montevideo", false, -3, "UY"],
  ["Rothera", false, -3, "UK"],
  ["Stanley", false, -3, "UK"],
  ["Halifax", false, -4, "CA"],
  ["Manaus", false, -4, "BR"],
  ["Caracas", false, -4, "VE"],
  ["São Paulo", false, -4, "BR"],
  ["Santiago", false, -4, "CL"],
  ["Lima", false, -5, "PE"],
  ["Indianapolis", false, -5, "US"],
  ["Quito", false, -5, "EC"],
  ["Toronto", false, -5, "CA"],
  ["London", false, 0, "UK"],
  ["Abidjan", false, 0, "CI"],
  ["Bamaco", false, 0, "ML"],
  ["Riyadh", "الرياض", 3, "SA"],
  ["Frankfurt", false, 1, "DE"],
  ["Zürich", false, 1, "CH"],
  ["Copenhagen", "København", 1, "DK"],
  ["Stockholm", false, 1, "SE"],
  ["Helsinki", "Helsingfors", 2, "FI"],
  ["Tallinn", false, 2, "EE"],
  ["Riga", false, 2, "LV"],
  ["Vilnius", false, 2, "LT"],
  ["Reykjavik", false, 0, "IS"],
  ["Oman", "عمان", 4, "OM"],
  ["Dubai", "دبي", 4, "AE"],
  ["Kabul", "کابل", 4.30, "AF"],
  ["Tashkent", "Тошкент", 5, "UZ"],
  ["Karachi", " کراچی", 5, "PK"],
  ["Ürümqi", "乌鲁木齐市", 6, "CN"],
  ["Omsk", "Омск", 6, "RU"],
  ["Dhaka", "ঢাকা", 6, "BD"],
  ["Phnom Pen", "រាជធានីភ្នំពេញ", 7, "KH"],
  ["Seoul", "서울", 9, "KR"],
  ["Kuala Lumpur", "ولايه ڤرسکوتوان کوالا لومڤور", 8, "MY"],
  ["Novosibirsk", "Новосибирск", 7, "RU"],
  ["Baikonur", "Байқоңыр", 6, "KZ"],
  ["Bangkok", "กรุงเทพมหานคร", 7, "TH"],
  ["Taipei", "臺北市", 8, "TW"],
  ["Singapore", "新加坡共和国", 8, "SG"],
  ["Jakarta", false, 9, "ID"],
  ["Adelaide", false, 9.3, "AU"],
  ["Vladivostok", "Владивосток", 10, "RU"],
  ["Sydney", false, 10, "AU"],
  ["Brisbane", false, 10, "AU"], 
  ["Melbourne", false, 10, "AU"],
  ["Nouméa", false, 11, "FR"],
  ["Auckland", false, 12, "NZ"],
  ["Suva", false, 12, "FJ"],
  ["Apia", false, 13, "WS"],
  ["Nukuʻalofa", false, 13, "TO"],
  ["Johannesburg", false, 2, "ZA"],
  ["Tehran", "تهران", 3.33, "IR"]
]
