export default [
    'il y avait un jumeau',
    'il y avait une greffe de cœur',
    'il y avait une taupe',
    'c’était son père',
    'il était déjà mort',
    'tout était dans sa tête',
    'c’était lui l’assassin',
    'elle se faisait vomir',
    'ses seins étaient refaits',
    'la gauche n’avait pas gagné',
    'tout le monde savait pour l’Abbé Pierre',
    'c’était la faute des pauvres',
    'il jouait à faire l’idiot',
    'c’était de la margarine',
    'Jean-Luc Mélenchon était une créature extraterrestre assoiffée de sang qui voulait imposer le marxisme martien sur Terre',
    'elle chantait en playback',
    'c’était le trans de « transport »',
    'c’était pas ce que vous croyiez',
    'c’était juste un quiproquo',
    'le produit était tombé dans le verre par accident et il l’avait trouvé dans le bar, il était pas venu avec',
    'il pouvait tout à fait reprendre sa carrière après ça',
    'les frappes étaient réalisées avec un marteau piqueur chirurgical',
    'il y avait pas tant de missiles cachés dans les salons à côté des télévisions',
    'il y a peut-être eu quelques victimes collatérales mais en fait ça a été un massacre mais en fait c’était ça depuis le début ???',
    'la démocratie est une marque déposée qu’il faut payer pour utiliser',
    'les actionnaires s’en branlent du bien commun',
    'les dauphins sont des violeurs',
    'ce serait pas les seuls mais en fait on pourrait parfois séparer l’œuvre de l’artiste',
    'quand on disait « tout est possible aujourd’hui » on pensait que c’était technique mais c’était moral',
    'on aurait pu prévoir apparemment',
    'certains des « en fait » étaient faux',
    'plus personne ne supporte les « en fait »'
]
