const LABELS = [
  'Abandoned working trail',
  'Archipelago of Solitude',
  'Avant-garde of the 60s',
  'A pleasant moment by the fire',
  'Base camp',
  'Black out',
  'Body of an adventurer who disappeared in 1976',
  'Border not recognized by the international community',
  'Brownian motion',
  'Cave of regrets',
  'Cascade of spatial coordinates',
  'Chasm of the ego',
  'Chemical submission',
  'Cosmic microwave background',
  'Dark matter',
  'Decimal Valley',
  'Dream I had of you',
  'Dry lake',
  'Entertainment',
  'Exploration between emptiness and fullness',
  'Fails desert',
  'Few things here',
  'Forsaken construction',
  'Forgotten pictorial expedition',
  'Ghost bug',
  'Godwin\'s law',
  'Hill of the Anons',
  'Homo sapiens (or almost)',
  'Identitarian closure',
  'Ignorance',
  'Imposter syndrome pass',
  'Informational subversion',
  'Landslide',
  'Lost ideas',
  'Mail received in 2009, still unread',
  'Mind control',
  'Mt Attractor',
  'Non-reciprocity',
  'Not a safe place',
  'Nothing',
  'Nuclear briefcase',
  'One wall too many',
  'Others ideas',
  'Popular opinion has never been proven',
  'Procrastination cirque',
  'Psychological war',
  'Simulacre',
  'Questionable circumstances',
  'People on Linkedin',
  'Pre-Columbian civilization',
  'Primitive animal',
  'Radio interference',
  'Random choice between two decisions',
  'Red line (faded)',
  'Relative success',
  'Retro-futurism',
  'Replicable experiment',
  'Ruin',
  'Shipwreck in real time',
  'Solar flares',
  'Subduction zone',
  'Trickle down (not the economic theory, this one actually exists)',
  'Tectonic plate convergence',
  'Temple of Randomness',
  'The first image of your favourite film',
  'The moment we are living through',
  'The remnants of Net Art',
  'The well of wealth',
  'Two dead projects buried here',
  'Unknown source',
  'Your first souvenir',
  'Virtual, until there is evidence to the contrary',
  'Well-documented scientific theory',
  'Wind shear'
]

export { LABELS }
