const LABELS = [
  'Abandoned working trail',
  'Avant-garde of the 60s',
  'A pleasant moment by the fire',
  'Cave of regrets',
  'Cascade of spatial coordinates',
  'Chasm of the ego',
  'Decimal Valley',
  'Dream I had of you',
  'Dry lake',
  'Fails desert',
  'Few things here',
  'Forsaken construction',
  'Ghost bug',
  'Hill of the Anons',
  'Identitarian closure',
  'Landslide',
  'Lost ideas',
  'Mail received in 2009, still unread',
  'Mt Attractor',
  'Not a safe place',
  'Others ideas',
  'Popular opinion has never been proven',
  'Simulacre',
  'Questionable circumstances',
  'People on Linkedin',
  'Relative success',
  'Retro-futurism',
  'Ruin',
  'Trickle down (not the economic theory, this one actually exists)',
  'Tectonic plate convergence',
  'Temple of Randomness',
  'The first image of your favourite film',
  'The remnants of Net Art',
  'Two dead projects buried here',
  'Unknown source',
  'Your first souvenir',
  'Virtual, until there is evidence to the contrary',
  'Well-documented scientific theory'
]

export { LABELS }
