const LABELS = [
  'Abandoned working trail',
  'Archipelago of Solitude',
  'Avant-garde of the 60s',
  'A pleasant moment by the fire',
  'Cave of regrets',
  'Cascade of spatial coordinates',
  'Chasm of the ego',
  'Decimal Valley',
  'Dream I had of you',
  'Dry lake',
  'Entertainment',
  'Exploration between emptiness and fullness',
  'Fails desert',
  'Few things here',
  'Forsaken construction',
  'Ghost bug',
  'Hill of the Anons',
  'Homo sapiens (or almost)',
  'Identitarian closure',
  'Imposter syndrome pass',
  'Informational subversion',
  'Landslide',
  'Lost ideas',
  'Mail received in 2009, still unread',
  'Mt Attractor',
  'Non-reciprocity',
  'Not a safe place',
  'Nothing',
  'One wall too many',
  'Others ideas',
  'Popular opinion has never been proven',
  'Procrastination cirque',
  'Psychological war',
  'Simulacre',
  'Questionable circumstances',
  'People on Linkedin',
  'Primitive animal',
  'Random choice between two decisions',
  'Red line (faded)',
  'Relative success',
  'Retro-futurism',
  'Ruin',
  'Shipwreck in real time',
  'Trickle down (not the economic theory, this one actually exists)',
  'Tectonic plate convergence',
  'Temple of Randomness',
  'The first image of your favourite film',
  'The moment we are living through',
  'The remnants of Net Art',
  'The well of wealth',
  'Two dead projects buried here',
  'Unknown source',
  'Your first souvenir',
  'Virtual, until there is evidence to the contrary',
  'Well-documented scientific theory'
]

export { LABELS }
