const SENTENCES = [
  "the same, otherwise ",
  "a rule that bends ",
  "form as protocol ",
  "variation within the system ",
  "structure as a starting point",
  "the grid neither shrinks nor grows",
  "a cycle like a breath",
  "a cascade reaction",
  "a dictionary of behaviours",
  "mapping the visible",
  "the tension between rule and variation",
  "the ordered proliferation of possibilities",
  "absorbing internal disorder",
  "naming what the program can do",
  "randomness as co-author",
  "controlled irregularity",
  "the voids of one are the solids of the other",
  "the grid as epistemology",
  "the discretization of the continuous",
  "made rather than rendered",
  "opacity is constructed, line by line",
  "nothing but accumulation",
  "the protocol rising to the surface",
  "orphaned syllables",
  "neither one nor the other",
  "a mathematical fingerprint",
  "visual poetry from coordinates",
  "rigid rules, organic results",
  "where meaning dissolves into texture",
  "language as a substrate",
  "on the edge of legibility",
  "a visual archaeology of the loop",
  "chaotic and predictable",
  "a phantom relief",
  "collision, not fusion",
  "order arising from disorder",
  "vibrating surfaces",
  "one captured, the other calculated",
  "the porous boundary",
  "the program reinterprets its own work",
  "only on dark squares",
  "a definitive halt",
  "a decorative or painterly gesture?",
  "an incantation repeated endlessly",
  "the infra-thin"
]

export { SENTENCES }
